version: '2.0'
services:
  web:
    image: vishnuatrai/nginx-trusty:initial
    build:
      context: ./containers/web
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - external

  app:
    image: unicorn-app
    build:
      context: .
      dockerfile: ./containers/app/Dockerfile
    command: foreman start -f Procfile
    ports: 
      - "3000:3000"
    volumes: 
      - .:/app/sinatra-docker
    depends_on:
      - db
      - cache
    networks:
      - external
      - internal1

  db:
    image: vishnuatrai/mysql-trusty:initial
    build: 
      context: ./containers/db
      dockerfile: ./Dockerfile
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - internal1

  cache:
    image: vishnuatrai/redis-trusty:initial
    build:
      context: ./containers/cache
      dockerfile: ./Dockerfile
    ports: 
      - "6379:6379"
    networks:
      - internal1

networks:
  external:
    driver: bridge
  internal1:
    driver: bridge

volumes:
  data:
    driver: local
